### ISSUE TITLE
How to produce fragmented mp4 files?

### ISSUE THREAD

**Issue by ivanjaros** [nareix/joy4#121]
Related to https://github.com/nareix/joy4/issues/120 the issue with [media source](https://developer.mozilla.org/en-US/docs/Web/API/MediaSource) is that it will simply not play mp4 files that are not **fragmented**. Hence I am asking - how to produce fragmeented mp4 files?

As I understand it, standard mp4 file will have one big chunk of data in the container whereas fragmented mp4 will have multiple chuks of data - individual atoms, hence the reader can start playing immediately after being able to read the first atom and proceed to the other one. So it is only a matter of mp4 muxer to write packets in such form. The _writePacket_ method would need to be changed or allow for a flag argument.

Some info: https://stackoverflow.com/a/35180327/11493911

edit: seems it is more about the mp4io than mp4 muxer.

edit2: it looks like the mp4 muxer WriteHeader() will write the MDAT right away which essentially means that anything written by WritePacket will be put into this one big container. So I think that write header needs to stop doing this and it should be moved into write packet method, together with MOOF and trailers should just adjust the SIDX, as per the images in the SO post linked above.

just to get visual context, images from the SO above:

standard mp4 container("mono"):
![mp4-mono](https://user-images.githubusercontent.com/64546059/90533509-ed31a400-e178-11ea-972c-fafc53f03799.png)

fragmented mp4 container:
![mp-fragmented](https://user-images.githubusercontent.com/64546059/90533505-ec990d80-e178-11ea-82ce-7dd991801cd9.png)

**Comment by ivanjaros** [comment]
is looks that the mp4 muxer is outputting only mdat and moov fields. there is no ftyp field. and http://mp4parser.com/ plus looking at WriteTrailers shows that the moov follows mdat, which is strange.

**Comment by ivanjaros** [comment]
anyone interested in this should have a look at the https://github.com/edgeware/mp4ff

**Comment by cedricve** [comment]
@ivanjaros did you made any progress on this? Really interested in this!

**Comment by ivanjaros** [comment]
yes, i used another library but i abandoned the project since then so i don't remember

**Comment by cedricve** [comment]
no worries by this time, we already implemented the solution in Kerberos.io
