### ISSUE TITLE
404 not found for multiple channels example

### ISSUE THREAD

**Issue by g33kidd** [nareix/joy4#39]
Sorta new to this, just kinda playing around with this for fun. I can't seem to actually get the `http_flv_and_rtmp_server` example to work properly. When I try to use `ffplay` I just get a 404 error because the channel doesn't exist. But I can't seem to figure out why

**Comment by zuzana** [comment]
Hi, I'm having the same issue. Were you able to run the example in the end? If yes, what was the solution? Thanks.
