### ISSUE TITLE
how can i publish packet to other rtmp servers

### ISSUE THREAD

**Issue by hcwang512** [nareix/joy4#46]
hello guys, i want to use this library to receive rtmp data from one resource and publish the packet data to other rtmp servers.
i use code like this:
```
conn, err = rtmp.Dial(url)
conn.WritePacket(packet)
```
but i got error `connection reset by peer`, and i'm sure there is no other connections.
Any information would by helpful

**Comment by haormj** [comment]
@hcwang512 also I want to publish raw h264 to rtmp server over joy4, do you have some examples?
